name: Clean Old Snapshots
on:
  schedule: # execute every day 8:00
  - cron: "0 8 * * *"
  workflow_dispatch:

permissions:
  contents: write
jobs:
  clean:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Clean Artifacts
        uses: gradle/gradle-build-action@v2
        with:
          arguments: deleteOutdatedArtifacts -DjustTasks
        env:
          ORG_GRADLE_PROJECT_MAVEN_AUTHORIZATION: ${{ secrets.OSSRH_AUTHORIZATION }}
